spring:
  datasource:
    url: jdbc:h2:mem:bantuconnect;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: banturoot
    password:

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2-console

  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
